common: &common --group_configs default fl6_adam_lr1 office31
A: &A --config_names dann mcc
B: &B --config_names atdoc bsp
C: &C --config_names cdan im
D: &D --config_names bnm gvb
E: &E --config_names mcd mmd


commands:
- - python launch_one.py --src_domains amazon --target_domains dslr
  - *A
  - *common
- - python launch_one.py --src_domains amazon --target_domains webcam
  - *A
  - *common
- - python launch_one.py --src_domains dslr --target_domains amazon
  - *A
  - *common
- - python launch_one.py --src_domains dslr --target_domains webcam
  - *A
  - *common
- - python launch_one.py --src_domains webcam --target_domains amazon
  - *A
  - *common
- - python launch_one.py --src_domains webcam --target_domains dslr
  - *A
  - *common


- - python launch_one.py --src_domains amazon --target_domains dslr
  - *B
  - *common
- - python launch_one.py --src_domains amazon --target_domains webcam
  - *B
  - *common
- - python launch_one.py --src_domains dslr --target_domains amazon
  - *B
  - *common
- - python launch_one.py --src_domains dslr --target_domains webcam
  - *B
  - *common
- - python launch_one.py --src_domains webcam --target_domains amazon
  - *B
  - *common
- - python launch_one.py --src_domains webcam --target_domains dslr
  - *B
  - *common


- - python launch_one.py --src_domains amazon --target_domains dslr
  - *C
  - *common
- - python launch_one.py --src_domains amazon --target_domains webcam
  - *C
  - *common
- - python launch_one.py --src_domains dslr --target_domains amazon
  - *C
  - *common
- - python launch_one.py --src_domains dslr --target_domains webcam
  - *C
  - *common
- - python launch_one.py --src_domains webcam --target_domains amazon
  - *C
  - *common
- - python launch_one.py --src_domains webcam --target_domains dslr
  - *C
  - *common


- - python launch_one.py --src_domains amazon --target_domains dslr
  - *D
  - *common
- - python launch_one.py --src_domains amazon --target_domains webcam
  - *D
  - *common
- - python launch_one.py --src_domains dslr --target_domains amazon
  - *D
  - *common
- - python launch_one.py --src_domains dslr --target_domains webcam
  - *D
  - *common
- - python launch_one.py --src_domains webcam --target_domains amazon
  - *D
  - *common
- - python launch_one.py --src_domains webcam --target_domains dslr
  - *D
  - *common


- - python launch_one.py --src_domains amazon --target_domains dslr
  - *E
  - *common
- - python launch_one.py --src_domains amazon --target_domains webcam
  - *E
  - *common
- - python launch_one.py --src_domains dslr --target_domains amazon
  - *E
  - *common
- - python launch_one.py --src_domains dslr --target_domains webcam
  - *E
  - *common
- - python launch_one.py --src_domains webcam --target_domains amazon
  - *E
  - *common
- - python launch_one.py --src_domains webcam --target_domains dslr
  - *E
  - *common

