dataset: mnist
src_domains: mnist
target_domains: mnistm
max_epochs: 100
validation_interval: 2
patience: 5
num_workers: 2

validator: oracle
feature_layer: 6
optimizer: Adam
lr_multiplier: 1

num_trials: 100
n_startup_trials: 100
batch_size: 64
num_reproduce: 4

save_features: true
download_datasets: true
is_within_exp_group: true
start_with_pretrained: true